---
editor_options: 
  markdown: 
    wrap: 72
---

# Glossary

**Abomasum** The fourth digestive chamber of the digestive system of
most ruminants. The abomasum is located after the forestomachs (rumen,
reticulum and omasum) and before the first segment of the small
intestine (i.e., the duodenum); It is sometimes referred to as the
"true" stomach because of its acid-secreting ability, which is found in
most other mammalian species.

**Precision** 1. The degree with which a measurement is reproducible,
that is, yielding similar results when repeated (see also Accuracy). 2.
the number of significant digits to which a value has been reliably
measured.

**Abomasum** The fourth digestive chamber of the digestive system of
most ruminants. The abomasum is located after the forestomachs (rumen,
reticulum and omasum) and before the first segment of the small
intestine (i.e., the duodenum); It is sometimes referred to as the
"true" stomach because of its acid-secreting ability, which is found in
most other mammalian species.

**Allometric (Equation)** Allometric equations take the general form Y =
aMb, where Y is some biological variable, M is a measure of body size,
and b is some scaling exponent. See West et al. (2012) for more details.

**Allometry** The growth of body parts at different rates, resulting in
a change of body proportions.

**Abomasum** The fourth digestive chamber of the digestive system of
most ruminants. The abomasum is located after the forestomachs (rumen,
reticulum and omasum) and before the first segment of the small
intestine (i.e., the duodenum); It is sometimes referred to as the
"true" stomach because of its acid-secreting ability, which is found in
most other mammalian species.

**As-Is Basis** A method of expressing the concentration of a nutrient
in a feed. For example, a feed containing 12% crude protein on a dry
matter basis contains 12 g of protein for each 100 g of feed "as-is" (or
"fresh"). When feed ingredients are added to a mixer, they are weighted
on an "as-is" of "fresh" basis. See also "Dry Matter Basis.

**NA** The fourth digestive chamber of the digestive system of most
ruminants. The abomasum is located after the forestomachs (rumen,
reticulum and omasum) and before the first segment of the small
intestine (i.e., the duodenum); It is sometimes referred to as the
"true" stomach because of its acid-secreting ability, which is found in
most other mammalian species.

**Bezoar** A small stony concretion that may form in the stomachs of
certain animals, especially ruminants. Bezoars are caused by a buildup
of material in the gastrointestinal tract that the stomach can't digest.

**Bloat** A swelling of the left side of the cow caused by a frothy
material which prevents gases of fermentation from being eructed from
the rumen. Occurs primarily when cows are grazing certain species of
legumes especially, alfalfa. If not treated immediately, bloat can cause
death in a matter of hours. More...

**Buffer** A chemical substances, such as sodium bicarbonate, that can
maintain the pH of the rumen content around neutrality (pH = 6 to 7).
The pH is maintained by neutralizing the volatile fatty acids and other
organic acids produced by ruminal fermentation.

**Bull (Clean-Up)** A bull used for natural mating after mutiple
artificial insemination attempts have failed to establish pregnancy.

**Calorie** A unit of heat that can be used to measure the amount of
energy in a feed or a ration. A calorie is the amount heat required to
raise the temperature of 1 gram of water from 14.5 ° centigrade to 15.5
° centigrade.

**Calve (To)** (see Parturition)

**Carbohydrate** Any of a group of chemical compounds, including sugars,
starches, and cellulose, containing only carbon, hydrogen, and oxygen,
with a ratio of hydrogen to oxygen of 2:1.

**Carbon Dioxide (Co2)** A gas produced by combustion or oxidation of
organic matter. Carbon dioxide is also produced in large quantities
during ruminal fermentation.

**Catabolism** The part of the metabolism in which metabolites are
oxidized for the production of work and heat.

**Catalyst** A substance present in small amounts that increases the
rate of chemical or biochemical reactions without being consumed in the
process.

**Cell Wall** Fibrous structure that provides rigidity to the plant. The
cell wall is composed of digestible fibrous carbohydrates (cellulose;
hemicellulose and pectin) and an indigestible phenolic compounds (e.g.,
lignin and tannin).

**Cellulose (C6h10o5)N:** A polymer - long chain- of glucose units.
Cellulose is the most abundant organic matter in the world. It is a
major component of plant cell wall. Ruminant can use cellulose as an
energy source because of fermentation by bacteria in the rumen.

**Cereal** A plant in the grass family (gramineae), the seeds (i.e.,
grain) of which are used for human and animal food (e.g., maize, rice
and wheat).

**Chaff** Glumes, husk, or other seed coverings, together with the plant
parts, separated from seeds in threshing or processing.

**Chew (To)** To crush or grind (food) in the mouth by continued action
of the teeth with the help of the tongue (syn to masticate).

**Clinical** Involving or based on direct observation of the patient (a
clinical diagnosis). A clinical disease is a disease that can be
diagnosed by examination because of signs / symptoms of discomfort,
anomalies of the normal state

**Cob** The central core of an ear of corn.

**Colostrum** The thick and yellowish secretion collected from the
mammary gland at the first milking after calving. The colostrum is low
in lactose but normally high in total solid (24%). It is rich in fat,
proteins and antibodies that help the new born calf to fight infectious
diseases. The secretion collected from the second to the eighth milking
is referred to as "transition milk" because of it intermediate
composition between colostrum and whole milk.

**Concentrate** Feedstuffs usually rich in energy and coming from the
part of the plant that accumulate nutrient reserves for an embryo
(fruits, nuts, seeds and grains). The word concentrate is also used to
refer to the mixture of minerals and other supplements used to feed
dairy cattle.

**Crown** Base of the stem where roots arise

**Crude Protein** A measure of the amount of protein in a feed
determined as the amount of nitrogen multiplied by 6.25. The factor 6.25
is the average grams of protein that contains 1 gram of nitrogen. The
word "crude" refers to the fact that not all nitrogen in most feed is
exclusively in the form of protein. Because most feeds contain
non-protein nitrogen (NPN), crude protein generally overestimates the
actual protein content of a feed.

**Density** A measure of the concentration of matter per unit of volume
(e.g., g/l or kg/m3)

**Diarrhea** Pathologically excessive evacuation of watery feces.
Diarrhea may be due to an infectious agent (bacterial infection) or a
dietary imbalance.

**Digesta** The mixture of digestive secretion, bacterial population and
feeds undergoing digestion in the gastro-intestinal tract (such as rumen
content).

**Digestibility (Coefficient Of)** A measure of the proportion of a feed that is digestible. The digestibility of a nutrient is often measured asthe difference between the amount of nutrient ingested minus the amount
of nutrient excreted in the feces, expressed as a percentage of the
nutrient ingested: 100 x (intake - excreted)/intake.

If animals could completely metabolize (combust) the entire mass of feed they ate, there would be no need for excreting feces. Yet clearly, some fraction of the energy and nutrients in feed is not digested by the animal. In other words, some fraction of feed escapes being broken down into simpler molecules (digestion) and is instead excreted in feces.

The **apparent digestibility** of a feed is defined as the amount that apparently disappeared between entering the animal's mouth (Intake) and exiting in feces (Excreted). Most commonly, we calculate digestibility for the total gastrointestinal tract (the **total tract digestibility**) although it is possible to calculate digestibility for segments of the digestive tract (e.g., ruminal digestibility).

$$
 Apparent \space Digestibility \space (\%) = \frac{Intake \space  (g) - Excreted \space (g)}{Intake \space  (g)} * 100
$$

We call this "apparent" digestibility because is clearly visible to us. However, for some nutrients apparent digestibility is problematic. It does not take into account that feces contains not only undigested feed nutrients, but also losses from endogenous sources. For example, the regular turnover of cells and production of mucus in the gastrointestinal tract results in endogenous losses of protein. 

$$
 True \space Digestibility \space (\%) = \frac{Intake \space  (g) - \bigg( Excreted \space (g) - Endogenous \space (g) \bigg)}{Intake \space  (g)} * 100
$$

True digestibility includes a correction for endogenous losses of the nutrient.

**Dry Cow** A non-lactating cow. The dry period is the time between
lactation, when the cow is not secreting milk.

**Dry Matter** That part of the feed which is not water. It is usually
determined by the residual weight of a sample placed for a period of
time in a drying oven that removes the water from the sample. Usually,
the dry matter content of a feed is expressed as a percentage. For
example, an hay of 85% dry matter contains 85 g of dry matter for each
100 g of fresh feed.

**Dry Matter Basis** A method of expressing the concentration of a
nutrient in a feed. For example, a feed containing 12% crude protein on
a dry matter basis contains 12 g of protein for each 100 g of feed dry
matter

**Dry Matter Intake** Quantity of dry matter ingested by a cow in a 24 h
period. For example, a cow eating 18 kg of grass silage of 33% of dry
matter ingest 18 x 0.33 = 6 kg of grass silage dry matter.

**Duodenum** First part of the small intestine. The secretions of the
liver and pancreas are discharged into the duodenum.

**Ear (Of Corn)** The seed-bearing part of a cereal plant. An ear of
corn is composed of the grains, the cob, but not the husk, which are
removed during harvesting.

**Embryo** An organism, animal or vegetal, at its early stage of
development.

**Endosperm** The nutritive tissue of a plant seed, surrounding and
absorbed by the embryo.

**Energy Density** A measure of the concentration of energy in a feed or
a ration usually expressed as a unit of energy (megacalorie or
megajoule) per lb of dry matter or per kg of dry matter.

**Enrollment Plan** Method used to select cows which are eligible for
hormonal treatment (such as Ovsynch). For example, the enrollment plan
may be defined by the voluntary waiting period or a negative pregnancy
check.

**Enzyme** Usually a protein that accelerates a biochemical reaction at
body temperature, without being used up in the process (see also
catalyst).

**Epithelium** Membranous tissue, usually in a single layer, composed of
closely arranged cells separated by very little intercellular substance.
The epithelium forms the lining of the respiratory, intestinal, and
urinary tracts and the outer surface of the body.

**Excretion** The removal of a material from an organism. Example of
material excreted include tears, urine, feces, sweat and carbon dioxide.
Examples of an organism's organs involved in excretion include eyes,
bladder, rectum, skins and lungs.

**False Negative** An animal that tests as negative but who is actually
positive. The percent of false negative for a test can be calculated as
100 -- SENSITIVITY.

**False Positive** An animal that tests as positive but who is actually
negative. The percent of false positive for a test can be calculated as
100 -- SPECIFICITY.

**Fat** 1. Ester of glycerol and fatty acids. 2. Organic compound
containing carbon, hydrogen and oxygen, but as opposed to the
carbohydrates, fats have a ratio of hydrogen to oxygen well above 2:1.
Fats, as opposed to oils, are solids at room temperature and usually are
of animal origin.

**Fatty Acid** A chain of carbon terminated by an acid (carboxyl) group
(COOH). Fatty acids with less than 4 carbon units are volatile. Fatty
acids with 5 to 20 carbon units are usually found as part of fats and
oils.

**Fermentation (In The Rumen)** The transformation of carbohydrates in
absence of oxygen by rumen micro flora that produces volatile fatty
acids such as acetic acid, propionic acid and butyric acid, and gases
such as carbon dioxide (CO2) and methane (CH4).

**Fetus** The unborn young.

**Fiber (Dietary)** Nutrient of low energy density present in large
quantities in forages. Fiber is composed of structural carbohydrates
(cellulose and hemicellulose) and phenolic compounds. Fiber is important
for dairy cows because they stimulate rumination and promote a healthy
rumen environment for bacterial growth. However, in large amounts in the
diet, fiber may fill the rumen, limit intake of energy and constrain
milk production.

**Fibrous Carbohydrate** Hemicellulose and cellulose that can be
quantify by the neutral detergent fiber procedure.

**Fodder** Coarse feeds, such as straw, corn or sorghum stalks.

**Forage** Feed that stimulate rumination due to their long particle
size and their high content in fiber. Generally, forages are composed of
the leaves and stems (stalk of plants. The bacterial population of the
rumen allows the ruminant to digest forages.

**Forage To Concentrate Ratio** Usually expressed as two percentages.
The percentage of ration dry matter that is made up of forage and the
percentage of ration dry matter that is composed of concentrates. The
two total 100. For example a 50:50 forage to concentrate ratio means
that a cow eating 20 kg of dry matter of that ration would eat 10 kg of
concentrate dry matter and 10 kg of forage dry matter.

**Fructans** Is a polymer of fructose molecules generally, but not
always, found as "carbohydrate storage in cool season grasses (C3
plants). Tall fescue and perennial ryegrass tend to have the highest
levels of fructans when compared to other grasses under the same
conditions. Fructan is stored in vacuoles inside cells throughout the
plant where it is readily available as needed. In some species of grass
the lower part of the stem is a carbohydrate storage organ.

**Fructose (C6h12o6)** A sweet sugar occurring in many fruits and honey.

**Gastrointestinal Tract** The stomach and the intestine as a functional
unit.

**Germ** the embryo of a plant present in the seed.

**Germinate (To)** To begin to or to cause to grow (syn to sprout.

**Glucose: (C6h12o6)** A six carbon sugar which is the building block of
starch and cellulose. Glucose is rapidly fermented into volatile fatty
acids by ruminal bacteria.

**Glycerol** A three carbon sugar which form the backbone of
triglycerides and other fats.

**Goiter** An enlargement of the thyroid gland associated with iodine
deficiency and visible as a swelling at the front of the neck.

**Grain** Seed from cereal plants.

**Gramineae** Family of plants including rye grass, fescue, brome,
timothy and other herbaceous plants often referred to as grass. Cereals
are gramineous plants but often, they are considered apart from the
grass because they are cropped for the grain rather than the vegetative
parts of the plant.

**Grass** Any of the numerous plants of the family gramineae,
characteristically having narrow leaves and hollow, jointed stems (e.g.,
orchardgrass, ryegrass, bromegrass).

**Hay** A sun-dried forage. A method of preserving forage by cutting the
plant and letting it dry in the sun.

**Heat Period** A period of 9 to 24 hours preceding the ovulation during
which cows are receptive to bulls and exhibit a typical behavior of
mounting other cows or standing when mounted by other cows (or a bull).

**Heifer** A young female cow that has not yet given birth to a calf.

**Hemicellulose** A type of carbohydrate similar to cellulose except
that it contain not only glucose but also other 6 carbon sugars and also
5 carbon sugars.

**Hemoglobin** An iron rich protein found in the red blood cells which
function as a carrier of oxygen and carbon dioxide.

**Hull** Outer covering of grain or other seed, especially when dry
(syn: husk).

**Hunger** A strong desire for food.

**Husk** Outer envelop, usually green, of fruits and seeds, as around an
ear of corn (syn hull).

**Hydrochloric Acid (Hcl)** Strong acid secreted by the abomasum that
breaks down chemical bounds and thus contributes to the digestion of
feeds.

**Hydrolysis** Decomposition of a chemical compound by reaction with
water.

**Inflorescence** The arrangement of flowers on a stalk that
characterizes a plant species.

**International Units (Iu)** A unit of measurement of the amount of
biologically active vitamin in a feed or required in a diet.

**Kernel** The whole grain of a cereal. The meats of nuts and drupes
(single stoned fruits).

**Ketosis** A condition characterized by a lack of appetite, especially
for concentrates and an abnormally high concentration of ketone bodies
(e.g., acetone, hydroxy-butyrate) in the blood. Ketosis or acetonemia
occurs when the cow mobilizes large amounts of body reserves in early
lactation.

**Kilo Calorie (Kcal)** One thousand calories.

**Lactose** A disaccharide composed of a unit of glucose and a unit of
galactose. Also known as milk sugar, lactose is produced commercially
from whey.

**Laminitis** Inflammation of the sensitive vascular tissue of the hoof.

**Laxative** A feed or drugs that will induce bowel movements
(defecation) and relieve constipation.

**Leaf** Structure, usually flat and green that grows from a stem or
stalk of a plant and is responsible for photosynthesis.

**Legume** A plant of the family leguminosae which bears a pod that
splits into two valves with the seed attached to lower edge of one of
the valves (examples: pea, bean, clover, alfalfa, lespedeza). Also,
legumes are characterized by the nodules on their roots that allow these
plants to use atmospheric nitrogen reducing the need for nitrogen
fertilizer and improving soil fertility.

**Lignin** Indigestible phenolic compound which, as the plant matures,
is deposited in the cell wall and is responsible for the decrease in
digestibility of the cell wall carbohydrates.

**Limestone** A sedimentary rock, chiefly calcium carbonate (CaCO3),
containing variable amounts of magnesium. It is used as building stone,
but also as a source of calcium in ration of animals.

**Lipase** An enzyme that breaks down fat.

**Lipid** Any of the numerous fat or fat-like materials that are
generally insoluble in water, but soluble in common organic solvents.
Nutritionally, lipids contain about 2.25 times more energy then
carbohydrates.

**Lipoproteins** Protein coated packages that transport fats in the
bloodstream

**Lipotropic** Any compound that helps to prevent the accumulation of
abnormal or excessive amounts of fat in the liver, control blood sugar
levels, and enhance fat and carbohydrate metabolism.

**Liver** A large gland that has multiple functions, one of which is to
secrete bile and digestive enzymes that are mixed with the digesta
entering the duodenum.

**Lysine** One of the 20 amino acids constituting the building blocks of
proteins. Animals have a high requirement for lysine, and it is often
deficient in proteins of plants.

**Maintenance (Diet)** A diet that supplies the nutrients required to
maintain vital functions (heart beat, respiration) and assure a constant
body temperature.

**Maintenance (State)** A physiological state in which the animal is
neither gaining nor losing weight, performing work or expending
nutrients for any type of production.

**Mammals** A class of vertebrate animals distinguished by
self-regulating body temperature, hair, and in the female (a) milk
producing gland(s).

**Mastication** To grind or crush (food) with or as if with the teeth to
prepare it for swallowing and digestion (Syn: Chew).

**Mastitis** An infammation of the udder (often caused by a microbial
infection) resulting in pain and the secretion of milk with a high count
of white blood cells (referred to as somatic cell count).

**Mcal** Abbreviation for Megacalorie.

**Meal** 1. The episodes of feed ingestion throughout the day. 2. The
edible seed or other edible part of a grain, coarsely ground (as opposed
to flour which is finely ground).

**Mean (Statistics)** The mean of a normal distribution is the most
likely value (the value that has the lowest probability of being
"wrong"). The mean is the best measure of central tendency of a normal
distribution. With a normal distribution, approximately one-half of the
samples have values lower than the mean and one-half have values higher
than the mean.

**Megacalorie** One million calories.

**Metabolism** Refers to all of the changes that nutrients undergo after
they are absorbed from the digestive tract. Metabolism is divided into
anabolism and catabolism.

**Metabolite** A product of metabolism of nutrients.

**Metabolizable Protein** In ruminant nutrion, metabolizable protein,
often abbreviated MP, is the amount of digestible protein that reach the
small intestine, which is the source of amino acids absorbed into the
blood. The three main sources of MP include rumen undegraded protein
(the dietary protein fraction that has not been degraded in the rumen),
the microbial (bacterial) protein synthesized in the rumen from the
fermentation process, and the endogenous protein (intestinal digestive
enzymes and sloughed cells from the gastro-intestinal tract). The latter
source is minimal.

**Metritis** Inflammation of the uterus.

**Microbe** Animal or vegetal organism of microscopic dimension (syn
Microorganism).

**Microorganism** (see Microbe).

**Milk Fever** Condition that occurs immediately or within the first day
after calving. The cow has cold ears and a dry muzzle. This condition is
due to a calcium imbalance. As opposed to what the name implies, there
is no "fever", but rather a paralysis of the limbs.

**Mill (A)** 1. A building equipped with the machinery for grinding
grain into flour or meal. 2. A device or mechanism such as rotating
millstones, that grinds grain.

**Mill (To)** To grind, pulverize or break down into smaller particle
size in a mill.

**Mineral** 1. The inorganic chemical elements (e.g., calcium phosphorus
magnesium) determined by combusting a sample in a furnace and weighing
the mineral residue. 2. Minerals play major roles in numerous metabolic
processes. (syn Ash).

**Monogastric** Having one digestive cavity (i.e., one stomach).

**Morbidity** Morbidity is an incidence of ill health. It is measured in
various ways, often by the probability that a randomly selected
individual in a population at some date and location would become
seriously ill in some period of time. Contrast to mortality.

**Mortality** is incidence of death in a population. It is measured in
various ways, often by the probability that a randomly selected
individual in a population at some date and location would die in some
period of time. Contrast to morbidity.

**Multiparous (Cow)** A cow that has given birth more than once.

**Net Energy Of Lactation (Nel)** The amount of energy in a feed which
is available for milk production and body maintenance. Feeds generally
are similar in total energy content but vary widely in the proportion of
the total energy which is available for maintenance and milk production.
The remainder of the energy in the feed is lost in the feces urine, gas
belched form the rumen and excess heat production by the cow. In the
cow, it takes 0.74 Mcal NEl to produce 1 kg of milk containing 4% fat
and the net energy content of most feed range from 0.9 to 2.2 Mcal NEl
per kg dry matter.

**Neutral Detergent Fiber (Ndf)** A measure of the amount of cell wall
in a feed determined by a laboratory procedure. Neutral detergent fiber
includes cellulose, hemicellulose and lignin.

**Non-Fiber Carbohydrate** Carbohydrates that are not part of the
neutral detergent fiber, but generally accumulate in the plant as energy
reserve (e.g., starch). These carbohydrates usually are more rapidly and
more completely digested than the fibrous carbohydrates (syn
Non-structural carbohydrate).

**Non-Protein Nitrogen (Npn)** Nitrogen that comes from a source other
than protein but may be used by a ruminant in the building of protein.
NPN sources include compounds such as urea and anhydrous ammonia, which
are used in feed formulations for ruminant only.

**Non-Structural Carbohydrate** (see non-fiber carbohydrate).

**Nutrient** The chemical substances found in feeds that can be used,
and are necessary, for the maintenance, production and health of the
animal. The main classes of nutrients are carbohydrates, fats, proteins,
minerals, vitamins and water.

**Nutrient Requirement** This refers to meeting the animal's need of the
various classes of nutrients for maintenance, growth, reproduction,
lactation and physical work.

**Obese** extremely fat.

**Oil** Lipid, usually of vegetal origin, which is liquid at room
temperature (as opposed to fats).

**Omasum** The third stomach of a ruminant between the reticulum and the
abomasum. It is characterized by the presence of muscular leaves that
may have an absorptive function.

**Organic Matter** Compounds composed of carbon oxygen hydrogen and
nitrogen. All living organisms are composed primarily of organic matter.
Fats, carbohydrates and proteins are examples of organic compounds.

**Orts** This is a German word that refers to leftovers of a meal. In
dairy nutrition the orts is the amount of feed refused from a daily
offering. In dairy nutrition research, orts must be sampled and analyzed
in order to calculate with precision the consumption of dry matter and
nutrients by the cow. Orts expressed as a percent of dry matter offered
is a criteria to determine whether an animal was fed ad libitum (Syn:
refusals).

**Ovulation** Release of an oocyte (i.e., egg) from a mature follicle.
In dairy cows, ovulation occurs 24 to 32 hours after the first standing
event of behavioral estrous. Similarly, ovulation occurs 24 to 32 hours
after an injection of Gonadotropin Releasing Hormone; (Gn-RH)
administered in the presence of a dominant follicle.

**Palatability** The taste and flavor property of a feedstuffs that make
them more or less acceptable to be eaten.

**Pancreas** An irregularly shaped gland that secretes pancreatic juice
into the duodenum and produces insulin that is released into the blood.

**Papillae (Reticulo-Rumen)** 1. Small projections on the inner surface
of the rumen and the reticulum wall that increase the surface area of
absorption of volatile fatty acids and other end-products of bacterial
fermentation.

**Papillae (Tongue)** Protuberances at the surface of the tongue that
detect the taste of a feed.

**Parturition** The act of giving birth (Syn Calving).

**Pepsin** A digestive enzyme found in the gastric juice that breaks
down proteins into peptides.

**Peptide** 1. At least 2 but not more that 100 amino acids linked
together by a peptic bound. 2. Product of pepsin digestion of proteins.

**Ph** A measure of acidity or alkalinity of a solution. Values range
from 0 (most acid) to 14 (most basic), with neutrality at pH 7.

**Phenolic (Compound)** Organic substance in which the carbon atoms are
linked together in a ring structure (also called aromatic structure).
Lignin is an example of phenolic compound.

**Photosynthesis** The process by which the chlorophyll of plants
converts carbon dioxide and water into simple sugars with the
simultaneous release of oxygen.

**Placenta** An organ that develops during pregnancy in female mammals.
It lines the uterus and partially envelopes the fetus, to which it is
attached by the umbilical cord. Following birth, the placenta, then
called the after birth, is normally expelled. The retention of the
placenta usually leads to bacterial infection of the uterus called
metritis.

**Pod** The structure that contains the seeds of leguminous plants. It
usually splits open after drying of the plant.

**Polish (To)** To free from coarseness; to refine.

**Polygastric** Having more than one digestive cavity; Having a stomach
divided into different chambers (e.g., ruminants).

**Population (Statistics)** The set of individuals, items, or data from
which a statistical sample is taken. In statistical terms, a population
is defined as a larger set from which samples are obtained.

**Pregnant** Having one or several fetus growing inside the uterus.

**Primiparous (Cow)** 1. A young cow that is pregnant for the first
time. 2. A cow that has given birth once.

**Protease** Digestive enzyme that breakdown proteins into peptides.

**Protein** A chain or multiple chains of amino acids (more than 100).
Proteins are composed of carbon, oxygen, hydrogen nitrogen (16% on
average,found in the form of amino acids) and often sulfur. Proteins
have important functions in the body. They are present in all plants and
animals and they are essential in the ration of animals. See also Crude
Protein.

**Protozoan** Most primitive form of life in the animal kingdom composed
of only one microscopic cell.

**Pylorus** The passage connecting the stomach (abomasum) to the
duodenum.

**Radicle** The part of a plant embryo that develops into the primary
root.

**Regurgitation** Reversal of the natural direction in which contents
flow through a tube or a cavity in the body. During rumination, rumen
contents are regurgitated through the esophagus in the mouth for further
mastication.

**Reticulo-Rumen** The first two stomachs of a ruminant comprised of the
reticulum and the rumen. A microbial population lives in the rumen and
enable the cow to digest dietary fiber. The digesta in the rumen and the
reticulum is being exchanged once about every 50 to 60 seconds under the
influence of a rhythmic cycle of contraction which also results in
passage of some digesta from the reticulum into the omasum through the
reticulo-omasal orifice.

**Reticulum** The second stomach of a ruminant in which folds of the
mucous membrane form hexagonal cells. Also called honeycomb stomach. The
reticulum is joined to the omasum by the reticulo-omasal orifice.

**Rhizobium** A type of bacteria that live in association with the roots
of legume plants and make the nitrogen of the air available to the
plants.

**Rhizome** A root-like usually horizontal stem growing under or along
the ground that sends out roots from its lower surfaces and leaves or
shoots from its upper surface.

**Rickets** A deficiency disease resulting from a lack of vitamin D or
lack of sunshine exposure, characterized by defective bone growth.

**Root** Part of the plant, usually under ground that maintain the
plant, withdraw water and other nutrient from the soil, and sometimes
accumulate reserves of nutrients.

**Rumen** The large first compartment of the stomach of a ruminant from
which food is regurgitated and in which cellulose in broken down by the
action of the symbiotic bacterial, protozoa, and fungal populations.

**Scour** see diarrhea.

**Secretion** The movement of a material from one place to another.
Secretion is often required to move a material to the place where it can
be excreted. Examples of materials secreted include all materials
excreted (see Excretion above), plus enzymes, hormones and saliva. The
organs that play a role in secretion include all those involved in
excretion, plus the digestive glands like salivary glands, pancreas,
liver and gallbladder and endocrine glands like the thyroid gland,
pituitary gland, and ovaries and testes.

**Seed** A fertilized and ripened plant ovule containing an embryo
capable of germinating to produce a new plant.

**Sensitivity** The probability that a test is positive, given that the
animal has the disease (See also specificity).

**Serum** The clear yellowish fluid obtained upon separating the clotted
whole blood into its liquid and solid (red and white blood cells)
components.

**Silage** Method of preservation of fresh forages based on the partial
fermentation of the sugars in absence of oxygen. Silage can be made in
various silos.

**Silo** Structure constructed to help preserving forages as silage.
Different types of silos includes: Tower silo, oxygen limiting silo,
trench silo, etc.

**Sinus** A cavity formed by a bending or curving; a dilated passage.

**Somatic Cells** (a) Any of the cells of a plant or animal except the
reproductive cells. (b) Milk somatic cells are primarily leukocytes
(white blood cells) and some epithelial cells shed from the lining of
the mammary gland. The leukocytes are derived from blood and consist of
macrophages, lymphocytes, and polymorphonuclear cells, primarily
neutrophils (PMN). Normal milk does contain somatic cells, and the
concentration of these cells is almost always less than 100,000 cells/ml
in milk from uninfected/uninflamed mammary quarters.

**Specificity** The probability that a test is negative, given that the
animal does not have the disease (see also sensitivity).

**Sphincter** A ring-like muscle that maintains constriction of a bodily
passage or orifice and opens upon relaxation.

**Sprout (To)** To grow or to develop quickly (syn to germinate).

**Stalk** The main stem of an herbaceous plant.

**Starch** Carbohydrate found chiefly in seeds, fruits, tubers, roots,
an stem pith of plants notably in corn, potatoes, wheat and rice. Warm
season grasses (C4 plants) store starch in chloroplasts in leaf tissue.
C4 grasses such as Bermuda Paspalum or Rhodes grasses grown under heat
stress may contain considerable starch in leafy tissue. Nutritionally,
it is referred to as non-structural carbohydrate as opposed to the
carbohydrate found in the neutral detergent fiber of the plant.

**Stem** The main upward growing axis of a plant, usually above the
ground and in direction opposite of the roots.

**Stillborn Calf** A calf born dead or that dies within 48 hours of
birth.

**Stover** Fodder; mature-cured stalks from which seeds have been
removed, such as stalks of corn or stalk of sorghum without heads.

**Straw** The plant residue remaining after separation of the seeds in
threshing. It includes chaff.

**Structural Carbohydrate** (see Fibrous carbohydrate).

**Subclinical** Without clinical manifestations; said of the early
stages or a very mild form of a disease, e.g. subclinical disease,
infection, parasitism, or when a disease is detectable by biological
tests but not by a clinical examination.

**Symbiosis** The intimate living together of two dissimilar organism in
any of various mutually beneficial relationships.

**Tannin** Highly complex phenolic compounds in plants that may play a
role of defense again microorganisms and possible predators (the
herbivores). Tannin binds and reduces the availability of proteins and
carbohydrates to ruminal microbes.

**Taste** Property of feed detected by some papillae of the tongue and
the roof of the mouth resulting in a positive or negative response to
further ingestion of the feed.

**Thyroid Gland** A two-lobed gland located in the throat and secreting
the hormone thyroxin, which regulates the iodine metabolism in the body.

**Timed Artificial Insemination** Method of AI breeding in which the
timing of artificial insemination (AI) is based on a hormonal protocol
that synchronizes the timing of ovulation. This is in contrast to timing
insemination based on direct or indirect detection of estrous behavior.
Hormonal protocols for Timed AI were developed in 1995 and have been
widely adopted by dairy producers for reproductive management.

**Total Mixed Ration (Tmr)** Mixture of the forages, concentrates,
minerals and vitamin supplements of a ration. The total mixed ration has
the advantage of offering a balanced ration at each meal rather than on
a 24 h basis.

**Triglyceride** A fat composed of three fatty acids and glycerol.

**Trypsin** Digestive enzyme secreted by the pancreas and responsible
for the break down of peptide bonds of proteins. Some plants contain a
trypsin inhibitor that prevent trypsin from functioning properly.

**Udder** Mammary gland of a cow.

**Ultra-Violet:** Ray in sunlight which enables vitamin D to be
synthesized under the skin.

**Underfeeding** Usually refers to feeding insufficient energy.

**Unsaturated Fat** Fat containing fatty acids that can accept hydrogen
atoms to saturate their structure (e.g., oleic, linoleic, linolenic and
arachidonic acids).

**Urea [Co(Nh2)2]** A nitrogen-containing organic compound found in
urine and other body fluids. Urea is synthesized from ammonia and carbon
dioxide. Urea can be used as fertilizer or as a source of nitrogen in
the ration of ruminants.

**Vegetative** The parts of plants that are involved in the growth as
opposed to the parts of plants involved in reproduction.

**Very Low Density Lipoprotein (Vldl)** Particles that carry cholesterol
and fat throughout the bloodstream. These particles are released from
the liver into the bloodstream. They are similar to chylomicrons which
originate from the gut because they both carry cholesterol and
triglycerides which are gradually released in the bloodstream to be
absorbed by body cells along the way. In the process of losing
triglycerides, the VLDLs grow smaller and turn into LDLs (Low Density
Lipoprotein) which have lost all their triglycerides.

**Vitamins** Complex organic substances occurring naturally in plants
and animal tissue and essential in small amounts for the proper
functioning of numerous metabolic processes.

**Volatile** Evaporating readily at normal temperature and pressure.

**Volatile Fatty Acids (Vfa)** Products of fermentation of carbohydrates
(and some amino acids) by the rumen microorganisms. Acetic acid,
propionic acid and butyric acid are the primary volatile fatty acids
which are absorbed through the rumen wall and used as an energy source
by the cow.

**Voluntary Waiting Period** The number of days between calving and
first attempt to breed a cow. A typical voluntary waiting period is 45
days. However, it may varies from less than 40 to 80 days depending on
farmer's preference and reproductive protocol in place on the farm.

**Whey** The liquid fraction that remains after the separation of curd
in cheese making. Its main food use is in the preparation of whey
cheese, whey drinks and fermented whey drinks. The main industrial uses
are in the manufacture of lactose, whey paste and dried whey.
